: ADD-SHADOW-RAM ( -- )
  FF D0 DO  I FREE-PAGE  ." ADDED " I . CR  1 +LOOP ;
ADD-SHADOW-RAM

: RAMDRIVE-READ ( W:A N -- )
  RAMDRIVE-PAGE SWAP @ 0 SWAPW
  1 0 <MOVE-SHADOW ;
: RAMDRIVE-WRITE ( W:A N -- )
  RAMDRIVE-PAGE SWAP DUPW @
  0= IF
    ALLOC-PAGE DUP >R -ROT ! R>
  THEN
  0
  1 0 <MOVE-SHADOW ;

: DUMPW ( W:A W:N -- )
  FORW DUPW @ .H SPACE 1+W NEXTW DROPW ;
: TYPEW ( W:A W:N -- )
  FORW DUPW @ EMIT 1+W NEXTW DROPW ;

CREATE MESSAGE S" HELLO!"
MESSAGE 80 RAMDRIVE-WRITE

ALLOC-PAGE 0 VARW COMPRESSED-BUFFER
( : TEST-RAMDRIVE
  COMPRESSED-BUFFER 0 RAMDRIVE-READ
  COMPRESSED-BUFFER TEXT-BUFFER
  DUPW 2 FF +W UNCOMPRESS
  TEXT-BUFFER SWAPW OVERW -W TYPEW ; )

COMPRESSED-BUFFER 80 RAMDRIVE-READ
COMPRESSED-BUFFER 6 TYPE
