: ADD-SHADOW-RAM ( -- )
  FF D0 DO  I FREE-PAGE DROP  1 +LOOP ;
ADD-SHADOW-RAM

: RAMDRIVE-BLOCK-ADR ( W:NA -- W:A )
  @  RAMDRIVE-PAGE SWAP ;
: RAMDRIVE-READ ( W:A W:NA -- ERR? )
  RAMDRIVE-BLOCK-ADR @ 0 SWAPW
  1 0 <MOVE-SHADOW
  FALSE ;
: RAMDRIVE-WRITE ( W:A W:NA -- ERR? )
  RAMDRIVE-BLOCK-ADR DUPW @
  0= IF
    ALLOC-PAGE DUP >R -ROT ! R>
  THEN
  0
  1 0 <MOVE-SHADOW
  FALSE ;

VPS-IP VARW BS-IP
CREATE BS-BLOCK# 4 ALLOT
: BS-READ ( W:A W:NA -- ERR? )
  ." BS-READ " DUPW 4 DUMP CR
  BS-BLOCK#  0 3  <MOVE
  BS-IP BS-BLOCK# BS-LOAD ;
: BS-WRITE ( W:A W:NA -- ERR? )
  BS-BLOCK#  0 3  <MOVE
  BS-IP BS-BLOCK# BS-STORE ;

CREATE RAMDRIVE-STRUCT
  ' RAMDRIVE-READ ,2
  ' RAMDRIVE-WRITE ,2

CREATE BS-STRUCT
  ' BS-READ ,2
  ' BS-WRITE ,2

CREATE BLOCK-DEVICES
  RAMDRIVE-STRUCT ,2
  BS-STRUCT ,2

2 VAR MAX-BLOCK-DEVICES
0 0 VARW FN-READ
0 2 VARW FN-WRITE

: BLOCK>DEVICE ( W:NA -- W:DEV-STRUCT )
  0 3 +W @ DUP
  MAX-BLOCK-DEVICES >= IF
    ." INVALID DEVICE: " .
    0 0 EXIT
  THEN
  2* 0 SWAP BLOCK-DEVICES +W @W ;
: BLOCK-FN ( W:IDX W:NA -- ERR? )
  BLOCK>DEVICE
  DUPW 0=W IF
    ( FIXME: ARGS LEFT ON STACK )
    DROPW DROPW TRUE EXIT
  THEN
  +W @W EXECUTE ;
: BLOCK-READ ( W:A W:NA -- ERR? )
  FN-READ OVERW BLOCK-FN ;
: BLOCK-WRITE ( W:A W:NA -- ERR? )
  FN-WRITE OVERW BLOCK-FN ;
