( SERIAL-INIT SLIP-TEST )

: INTERPRET-LINE
  COUNTW OVERW +W INTERPRET ;
: REPL BEGIN
    ."  OK" CR
    KERNAL-READ-LINE
    18 0 CURSOR! CR
    ( ." <" KERNAL-LINE-BUF COUNT TYPE ." >" CR )
    KERNAL-LINE-BUF INTERPRET-LINE
  AGAIN ;

: TEST-READ
  1 BLOCK# 0 3 +W !
  TEST-BUF BLOCK# BLOCK-READ
  NOT IF
    TEST-BUF TYPE-COMPRESSED
  ELSE
    ." BLOCK-READ FAILED" CR
  THEN ;

S" SILLYPASSWORD123" COUNT DROP
BS-KEY  0 10 <MOVE

: TEST-WRITE
  1 BLOCK# 0 3 +W !
  1 BLOCK# !
  TEST-BUF BLOCK# BLOCK-WRITE
  IF  ." BLOCK-WRITE FAILED" CR  THEN
  ;

SERIAL-INIT .( INITIALIZED RS-232) CR
SUNET-IP PING
SUNET-IP PING
REPL

