B0 00 SOURCE USER-SOURCE
USER-SOURCE ACTIVE
( KERNEL-SOURCE ACTIVE )

( SERIAL-INIT SLIP-TEST )

CREATE RAM-DRIVE 5 DUP , ALLOT
." LOADING TO RAM DRIVE OF SIZE " RAM-DRIVE @ . CR
BUILTIN-BLOCKS RAM-DRIVE READ-RAM-DRIVE

: --> ;

: LOAD-RAM-BLOCK ( N -- )
  0 SWAP RAM-DRIVE +W 1+W @ 0
  TEXT-BUFFER  TEXT-BUFFER 2 FF +W  UNCOMPRESS2
  TEXT-BUFFER SWAPW INTERPRET ;

EDITOR
