KERNEL-SOURCE ACTIVE

: MAIN
  ." HERE: " HERE@W .W CR
  ." KERNEL SOURCE: "
  KERNEL-SOURCE @W .W 
  KERNEL-SOURCE 1+W 1+W @W .W CR
  ." ,2: " ['] ,2 .W CR
  ( BEGIN AGAIN ) ;
MAIN

( SERIAL-INIT SLIP-TEST )

EDITOR
