7 VAR 600BAUD ( LARGEST THAT WORKS HERE )
2 VAR SERIAL-FILE
0 VAR DEFAULT-FILE

02 40 VARW PACKET-MAX-SIZE
0 0 VARW PACKET-READ-SIZE

CREATE PACKET-READ-BUF
PACKET-MAX-SIZE ALLOTW

( INIT RS-232 )
CREATE FN-SERIAL  2 , 600BAUD , 0 ,

: SERIAL-INIT ( -- )
  FN-SERIAL KERNAL-SETNAM
  SERIAL-FILE 2 0 KERNAL-SETLFS
  KERNAL-OPEN ;
: SERIAL-EMIT ( C -- )
  2 KERNAL-CHKOUT  EMIT  0 KERNAL-CHKOUT ;
: SERIAL-KEY ( -- C )
  BEGIN
    02 9B @  02 9C @  <>
  UNTIL
  KERNAL-GETIN ;
: SLIP-ESC ( C -- C' )
  DUP DB = IF
    DROP SERIAL-KEY
    DUP DC = IF
      DROP C0 EXIT
    THEN
    DUP DD = IF
      DROP DB EXIT
    THEN
    ." SLIP ERR " .
  THEN ;
: SLIP-READ-DISCARD
  BEGIN  SERIAL-KEY C0 =  UNTIL ;
: SLIP-READ-PACKET
  SERIAL-FILE KERNAL-CHKIN
  0 0 BEGIN
    DUPW PACKET-MAX-SIZE =W IF
      DROPW
      0 0 TOW PACKET-READ-SIZE
      SLIP-READ-DISCARD
      DEFAULT-FILE KERNAL-CHKIN
      EXIT
    THEN
    SERIAL-KEY
    DUP C0 = IF
      DROP  TOW PACKET-READ-SIZE
      EXIT
    THEN
    SLIP-ESC >R
    DUPW PACKET-READ-BUF +W R> -ROT !
    1+W
  AGAIN ;
: PROCESS-PING
  ." PING FROM "
  PACKET-READ-BUF 0 C +W 4 DUMP ;
: PROCESS-ICMP
  PACKET-READ-BUF 0 14 +W @
  8 = IF
    PROCESS-PING EXIT
  ELSE
    ." UNKNOWN ICMP" CR
  THEN ;
: PROCESS-UDP
  ." UDP MESSAGE: "
  PACKET-READ-BUF 0 1C +W
  PACKET-READ-SIZE OVERW -W NIP TYPE CR ;
: PROCESS-IP
  PACKET-READ-BUF 0 9 +W @
  DUP 1 = IF
    DROP PROCESS-ICMP EXIT
  THEN
  11 = IF
    PROCESS-UDP EXIT
  ELSE
    ." UNKNOWN IP PROTOCOL"
  THEN ;

( : TERMINAL BEGIN
  KERNAL-KEY DUP EMIT SERIAL-EMIT
  AGAIN ; )

: SLIP-TEST
  BEGIN
    CR ." WAITING FOR PACKET" CR
    SLIP-READ-PACKET
    ." READ " PACKET-READ-SIZE .W
    ." BYTES" CR
    ( PACKET-READ-BUF PACKET-READ-SIZE NIP DUMP )
    PROCESS-IP
  AGAIN ;
