7 VAR 600BAUD ( LARGEST THAT WORKS HERE )
2 VAR SERIAL-FILE
0 VAR DEFAULT-FILE

02 40 VARW PACKET-MAX-SIZE
0 0 VARW PACKET-READ-SIZE
0 0 VARW PACKET-WRITE-SIZE

CREATE PACKET-READ-BUF
PACKET-MAX-SIZE ALLOTW

CREATE PACKET-WRITE-BUF
PACKET-MAX-SIZE ALLOTW

CREATE MY-IP A , 0 , 0 , 1 ,

( INIT RS-232 )
CREATE FN-SERIAL  2 , 600BAUD , 0 ,

: SERIAL-INIT ( -- )
  FN-SERIAL KERNAL-SETNAM
  SERIAL-FILE 2 0 KERNAL-SETLFS
  KERNAL-OPEN
  SERIAL-FILE KERNAL-CHKIN
  KERNAL-GETIN ( FIRST BYTE IS BAD )
  DEFAULT-FILE KERNAL-CHKIN
  ;
: SLIP-EMIT ( C -- )
  DEFAULT-FILE KERNAL-CHKOUT
  ." [" DUP .H ." ]" SPACE
  SERIAL-FILE KERNAL-CHKOUT
  DUP C0 = IF
    DROP DB EMIT DC EMIT EXIT
  THEN
  DUP DB = IF
    DROP DB EMIT DD EMIT EXIT
  THEN
  EMIT ;
: SLIP-WRITE-PACKET ( -- )
  SERIAL-FILE KERNAL-CHKOUT
  C0 EMIT
  PACKET-WRITE-BUF PACKET-WRITE-SIZE FORW
    DUPW @ SLIP-EMIT  1+W
  NEXTW DROPW
  C0 EMIT
  DEFAULT-FILE KERNAL-CHKOUT ;
: SERIAL-KEY ( -- C )
  BEGIN
    KERNAL-GETIN
    02 97 @ 8 AND 0= SKIP
    DROP
  AGAIN ;
: SLIP-ESC ( C -- C' )
  DUP DB = IF
    DROP SERIAL-KEY
    DUP DC = IF
      DROP C0 EXIT
    THEN
    DUP DD = IF
      DROP DB EXIT
    THEN
    ." SLIP ERR " .
  THEN ;
: SLIP-READ-DISCARD
  BEGIN  SERIAL-KEY C0 =  UNTIL ;
: SLIP-READ-PACKET
  SERIAL-FILE KERNAL-CHKIN
  0 0 BEGIN
    DUPW PACKET-MAX-SIZE =W IF
      DROPW
      0 0 TOW PACKET-READ-SIZE
      SLIP-READ-DISCARD
      DEFAULT-FILE KERNAL-CHKIN
      EXIT
    THEN
    SERIAL-KEY
    DUP C0 = IF
      DROP  TOW PACKET-READ-SIZE
      EXIT
    THEN
    SLIP-ESC >R
    DUPW PACKET-READ-BUF +W
    R> -ROT !
    1+W
  AGAIN ;
: PROCESS-PING
  ." PING FROM "
  PACKET-READ-BUF 0 C +W 4 DUMP CR ;
: PROCESS-ICMP
  PACKET-READ-BUF 0 14 +W @
  DUP 8 = IF
    DROP PROCESS-PING EXIT
  0= IF
    ." PONG FROM"
    PACKET-READ-BUF 0 C +W 4 DUMP CR
  ELSE
    ." UNKNOWN ICMP" CR
  THEN ;
: PROCESS-UDP
  ." UDP MESSAGE: "
  PACKET-READ-BUF 0 1C +W
  PACKET-READ-SIZE OVERW -W NIP TYPE CR ;
: PROCESS-IP
  PACKET-READ-SIZE 0 14 <W IF
    EXIT
  THEN
  PACKET-READ-BUF 0 9 +W @
  DUP 1 = IF
    DROP PROCESS-ICMP EXIT
  THEN
  11 = IF
    PROCESS-UDP EXIT
  ELSE
    ." UNKNOWN IP PROTOCOL"
  THEN ;
: CHECKSUM ( W:A W:N -- W:X )
  ( TODO: AVOID WRITING TO BUFFER )
  DUP 1 AND 0<> IF
    OVERW OVERW +W 0 -ROT !
  THEN
  0 0 SWAPW 1+W 2/W FORW
    OVERW @W SWAP 1C+W
    SWAPW 1+W 1+W SWAPW
  NEXTW
  SWAPW DROPW
  FF FF XORW ;
: ,@ ( W:A -- W:A+1 )
  DUPW @ , 1+W ;
: 4,@ ,@ ,@ ,@ ,@ ;
: IP-BUILD-HEADER ( W:SRC W:DEST PROTO -- )
  HERE@W >RW
  PACKET-WRITE-BUF HERE!W
  45 , 0 , PACKET-WRITE-SIZE SWAP ,2
  12 , 34 , 40 , 0 ,
  40 , ( PROTO ) , 0 , 0 ,
  SWAPW 4,@ DROPW 4,@ DROPW
  R>W HERE!W
  PACKET-WRITE-BUF  0 14  CHECKSUM SWAP
  PACKET-WRITE-BUF  0 A +W  !W
  ;
: !+ ( W:A C -- W:A+1 )
  -ROT  DUPW >RW  !  R>W 1+W ;
: !+W ( W:A W:X -- W:A+2 )
  OVERW !W 1+W 1+W ;
0 1 VARW PING-SEQ
AB BA VARW PING-ID
: ICMP-PING ( W:DEST -- )
  0 24 TOW PACKET-WRITE-SIZE
  MY-IP SWAPW 1 IP-BUILD-HEADER
  PACKET-WRITE-BUF 0 14 +W
  8 !+ 0 !+ 0 !+ 0 !+
  PING-ID SWAP !+W  PING-SEQ SWAP !+W
  8 FOR  I !+  NEXT
  DROPW
  PACKET-WRITE-BUF 0 14 +W  0 10  CHECKSUM SWAP
  PACKET-WRITE-BUF 0 16 +W !W
  SLIP-WRITE-PACKET
  PING-SEQ 1+W TO PING-SEQ
  PING-ID 1+W TO PING-ID
  ;
: PACKET-INFO
  ." READ PACKET WITH " PACKET-READ-SIZE .W
  ." BYTES" CR
  PACKET-READ-BUF PACKET-READ-SIZE NIP DUMP CR
  ." HEADER CHECKSUM: "
  PACKET-READ-BUF 0 14 CHECKSUM .W CR ;
CREATE OTHER-IP A , 0 , 0 , 2 ,
: SLIP-TEST
  OTHER-IP ICMP-PING CR
  OTHER-IP ICMP-PING CR
  BEGIN
    CR ." WAITING FOR PACKET" CR
    SLIP-READ-PACKET
    ( PACKET-INFO )
    PROCESS-IP
  AGAIN ;
